services:
  - type: web
    name: chat-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node index.js

  - type: web
    name: chat-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm run build
    staticPublishPath: build
  